feat: Update merge-to-nonprod and optimize code for rebase-nonprod too
CleverShuttle/gh-composite-actions pull request #54
Opened 2023-01-05 18:07 UTC by skromberg

Refs: OMG-2941

2023-01-05 19:03 UTC, monoclev requested changes
Huh, quite tricky stuff :exploding_head:

I did not fully understand what is going on. Could you reply to my current comments? Especially renaming `BRANCH_NAME` as suggested in one of the comments should make the code easier to understand and I'm eager to do another review then :muscle: 

Thank you @skromberg :100:

2023-01-05 19:03 UTC, monoclev commented on actions/merge-to-nonprod/action.yml
> +        BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
Please do not use `BRANCH_NAME` here and in `"Prepare nonprod"` as it refers to different branches and `BRANCH_NAME` does not show which branch is referred to. Please use `PR_BRANCH` here and `TARGET_BRANCH` in `"Prepare nonprod"`.

2023-01-05 19:05 UTC, skromberg commented on actions/merge-to-nonprod/action.yml
> +        git push --force-with-lease origin nonprod
https://stackoverflow.com/a/52823955

> force overwrites a remote branch with your local branch.

> --force-with-lease is a safer option that will not overwrite any work on the remote branch if more commits were added to the remote branch (by another team-member or coworker or what have you). It ensures you do not overwrite someone elses work by force pushing.

2023-01-05 19:25 UTC, skromberg commented on actions/merge-to-nonprod/action.yml
> +        BRANCH_NAME: ${{ steps.branch-name.outputs.base_ref_branch }}
```
default_branch: master
current_branch: feat/merge_to_nonprod
base_ref_branch: master
github.head_ref: feat/merge_to_nonprod
```

> nonprod branch exists. Merging 'master'

2023-01-05 19:29 UTC, skromberg commented on actions/merge-to-nonprod/action.yml
> +        BRANCH_NAME: ${{ steps.branch-name.outputs.base_ref_branch }}
```bash
Already up to date.
Run set -o nounset -o errexit
Merge feature branch 'feat/merge_to_nonprod' to nonprod
Merge made by the 'ort' strategy.
 .github/workflows/build-pull-request-and-deploy-nonprod.yml | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)
Run git push --force-with-lease origin nonprod
To https://github.com/CleverShuttle/business-area-service
   52f17b7..a7f5435  nonprod -> nonprod
```

2023-01-09 11:27 UTC, skromberg commented on actions/create-nonprod-changelog/generate-nonprod-changelog.js
>  console.log(output);
🧐 https://clevershuttle.slack.com/archives/C011Z4F88N6/p1673258378509749

2023-01-09 17:36 UTC, monoclev approved these changes
Great work, thank you @skromberg :100: :confetti_ball:

2023-01-09 17:36 UTC, monoclev commented on actions/check-merge-to-nonprod/action.yml
> +description: 'Checks if it is possible to merge the current branch into nonprod'
:partying_face: :balloon:

2023-01-09 17:36 UTC, monoclev commented on actions/create-nonprod-changelog/generate-nonprod-changelog.js
>  console.log(output);
:partying_face: - the branch is no longer available because I deleted the [update-parent-pom](https://github.com/CleverShuttle/driver-profile-service/tree/update-parent-pom) branch after merging the PR

2023-01-09 18:57 UTC, skromberg commented on actions/merge-to-nonprod/action.yml
> +      shell: bash {0}
https://stackoverflow.com/a/73069669

2023-01-10 08:23 UTC, monoclev commented on actions/merge-to-nonprod/action.yml
> +      shell: bash {0}
Ok, so this is some form of parameter substitution with replaces `{0}` by `-e` :+1: Thank you @skromberg

2023-01-13 10:18 UTC, merged